/* Central Celulares: dados editaveis.
   Numeros de WhatsApp, modelos, produtos e textos (PT/ES) ficam so aqui.
   Precos e produtos abaixo sao DE EXEMPLO ate o Jackson confirmar. */
window.CC = {
  wa: {
    br: { number: "5545998353303", label: "+55 45 99835-3303" },
    py: { number: "595995624887", label: "+595 995 624 887" },
  },
  langRoute: { pt: "br", es: "py" },
  mapQuery: "Shopping Gebai, Av. Piribebuy, Ciudad del Este, Paraguay",

  defects: ["screen", "battery", "charge", "power", "water", "camera", "audio", "buttons", "software", "other"],

  models: {
    iPhone: [
      ["iPhone 17", ["iPhone 17 Pro Max", "iPhone 17 Pro", "iPhone Air", "iPhone 17"]],
      ["iPhone 16", ["iPhone 16 Pro Max", "iPhone 16 Pro", "iPhone 16 Plus", "iPhone 16", "iPhone 16e"]],
      ["iPhone 15", ["iPhone 15 Pro Max", "iPhone 15 Pro", "iPhone 15 Plus", "iPhone 15"]],
      ["iPhone 14", ["iPhone 14 Pro Max", "iPhone 14 Pro", "iPhone 14 Plus", "iPhone 14"]],
      ["iPhone 13", ["iPhone 13 Pro Max", "iPhone 13 Pro", "iPhone 13", "iPhone 13 mini"]],
      ["iPhone 12", ["iPhone 12 Pro Max", "iPhone 12 Pro", "iPhone 12", "iPhone 12 mini"]],
      ["iPhone 11", ["iPhone 11 Pro Max", "iPhone 11 Pro", "iPhone 11"]],
      ["Anteriores", ["iPhone SE (2022)", "iPhone SE (2020)", "iPhone XS Max", "iPhone XS", "iPhone XR", "iPhone X", "iPhone 8 Plus", "iPhone 8", "iPhone 7 Plus", "iPhone 7"]],
    ],
    Samsung: [
      ["Galaxy S", ["S25 Ultra", "S25+", "S25", "S24 Ultra", "S24+", "S24", "S24 FE", "S23 Ultra", "S23+", "S23", "S22 Ultra", "S22"].map((m) => "Galaxy " + m)],
      ["Galaxy A", ["A56", "A36", "A26", "A16", "A06", "A55", "A35", "A25", "A15", "A05", "A54", "A34", "A24", "A14", "A04"].map((m) => "Galaxy " + m)],
      ["Galaxy Z", ["Galaxy Z Fold7", "Galaxy Z Flip7", "Galaxy Z Fold6", "Galaxy Z Flip6"]],
    ],
    Xiaomi: [
      ["Redmi Note", ["Redmi Note 14 Pro+", "Redmi Note 14 Pro", "Redmi Note 14", "Redmi Note 13 Pro+", "Redmi Note 13 Pro", "Redmi Note 13", "Redmi Note 12 Pro", "Redmi Note 12"]],
      ["Redmi", ["Redmi 14C", "Redmi 13C", "Redmi 13", "Redmi 12C", "Redmi 12", "Redmi A5", "Redmi A3"]],
      ["Poco", ["Poco X7 Pro", "Poco X7", "Poco X6 Pro", "Poco X6", "Poco F6", "Poco M6"]],
      ["Xiaomi", ["Xiaomi 15", "Xiaomi 14T", "Xiaomi 14", "Xiaomi 13T"]],
    ],
    Motorola: [
      ["Moto G", ["G85", "G84", "G75", "G55", "G54", "G35", "G34", "G24", "G15", "G05"].map((m) => "Moto " + m)],
      ["Moto E", ["E15", "E14", "E13", "E22"].map((m) => "Moto " + m)],
      ["Edge", ["Edge 50 Pro", "Edge 50 Fusion", "Edge 40 Neo", "Edge 40", "Edge 30"].map((m) => "Motorola " + m)],
      ["Razr", ["Razr 50", "Razr 40"].map((m) => "Motorola " + m)],
    ],
  },

  products: [
    { id: "case", cat: "protect", price: 5, featured: true },
    { id: "silicone", cat: "protect", price: 4 },
    { id: "glass", cat: "protect", price: 3 },
    { id: "charger", cat: "power", price: 9, featured: true },
    { id: "cable", cat: "power", price: 3 },
    { id: "bank", cat: "power", price: 15 },
    { id: "tws", cat: "audio", price: 12, featured: true },
    { id: "wired", cat: "audio", price: 3 },
    { id: "speaker", cat: "audio", price: 14 },
    { id: "carmount", cat: "mount", price: 6, featured: true },
    { id: "ring", cat: "mount", price: 2 },
    { id: "tripod", cat: "mount", price: 8 },
  ],

  i18n: {
    pt: {
      "doc.title": "Central Celulares | Assistência técnica de celular no Shopping Gebai, Ciudad del Este",
      "skip": "Ir para o conteúdo",
      "nav.services": "Defeitos",
      "nav.quote": "Orçamento",
      "nav.shop": "Vitrine",
      "nav.where": "Onde estamos",
      "nav.lang": "Idioma",
      "nav.cta": "Orçamento",
      "hero.eyebrow": "Assistência técnica · Shopping Gebai · Ciudad del Este",
      "hero.h1a": "Celular com defeito?",
      "hero.h1b": "Conserto rápido.",
      "hero.sub": "Diga o modelo e o defeito. O Jackson responde pelo WhatsApp com o orçamento, sem compromisso.",
      "hero.cta": "Fazer meu orçamento",
      "hero.wa": "Chamar no WhatsApp",
      "hero.where": "Av. Piribebuy, Centro",
      "dg.title": "Diagrama de um celular desmontado em camadas: tela, bateria, placa e carcaça",
      "dg.l1": "01 TELA",
      "dg.l2": "02 BATERIA",
      "dg.l3": "03 PLACA",
      "dg.l4": "04 CARCAÇA",
      "trust.label": "Diferenciais",
      "trust.1.t": "Orçamento sem compromisso",
      "trust.1.d": "Você só decide depois de ver o valor.",
      "trust.2.t": "Reparo rápido",
      "trust.2.d": "A maioria dos serviços sai no mesmo dia.",
      "trust.3.t": "Garantia no serviço",
      "trust.3.d": "O prazo é informado no orçamento.",
      "trust.4.t": "Peças testadas",
      "trust.4.d": "Conferimos tudo antes de entregar.",
      "how.h": "Como funciona",
      "how.1.t": "Conte o defeito",
      "how.1.d": "Escolha o modelo e marque o que está acontecendo.",
      "how.2.t": "Receba o orçamento",
      "how.2.d": "O Jackson responde pelo WhatsApp com valor e prazo.",
      "how.3.t": "Traga ao Shopping Gebai",
      "how.3.d": "Deixe o aparelho na loja e acompanhe pelo WhatsApp.",
      "svc.h": "Defeitos que a gente conserta",
      "svc.lead": "Toque no seu defeito para começar o orçamento. Não achou? Marque “Outro defeito” e descreva.",
      "svc.cta": "Pedir orçamento",
      "d.screen.n": "Tela quebrada",
      "d.screen.d": "Troca de tela e vidro, com ou sem imagem.",
      "d.battery.n": "Bateria",
      "d.battery.d": "Dura pouco, descarrega rápido ou está inchada.",
      "d.charge.n": "Não carrega",
      "d.charge.d": "Conector de carga, cabo ou placa.",
      "d.power.n": "Não liga",
      "d.power.d": "Diagnóstico de placa e fonte de energia.",
      "d.water.n": "Caiu na água",
      "d.water.d": "Limpeza de oxidação. Quanto antes, melhor.",
      "d.camera.n": "Câmera",
      "d.camera.d": "Foto borrada, preta ou lente quebrada.",
      "d.audio.n": "Som e microfone",
      "d.audio.d": "Alto-falante, auricular ou microfone sem funcionar.",
      "d.buttons.n": "Botões e sensores",
      "d.buttons.d": "Liga/desliga, volume e biometria.",
      "d.software.n": "Software",
      "d.software.d": "Travando, lento ou com erro de sistema.",
      "d.other.n": "Outro defeito",
      "q.h": "Faça seu orçamento",
      "q.lead": "Três passos e o Jackson já tem tudo para responder.",
      "q.badge": "Rascunho",
      "q.title": "Ordem de serviço",
      "q.s1": "1. Marca do aparelho",
      "q.s2": "2. Modelo",
      "q.s3": "3. O que está acontecendo?",
      "q.s3.hint": "Marque quantos precisar.",
      "q.model.ph": "Escolha o modelo",
      "q.model.first": "Escolha a marca primeiro",
      "q.model.other": "Outro modelo",
      "q.other.l": "Qual é o modelo?",
      "q.other.ph": "Ex.: Moto G54",
      "q.details.l": "Quer detalhar? (opcional)",
      "q.details.ph": "Ex.: caiu ontem, a tela acende mas não responde ao toque",
      "q.name.l": "Seu nome (opcional)",
      "q.name.ph": "Ex.: Maria",
      "q.route": "Enviar para",
      "q.route.br": "WhatsApp Brasil",
      "q.route.py": "WhatsApp Paraguai",
      "q.sum.h": "Resumo",
      "q.sum.device": "Aparelho",
      "q.sum.defects": "Defeitos",
      "q.sum.empty": "Ainda não escolhido",
      "q.send": "Enviar pelo WhatsApp",
      "q.hint": "Abre o WhatsApp com a mensagem pronta. Você confere antes de enviar.",
      "q.err.brand": "Escolha a marca do aparelho.",
      "q.err.model": "Escolha o modelo ou selecione “Outro modelo”.",
      "q.err.other": "Digite o modelo do aparelho.",
      "q.err.defects": "Marque pelo menos um defeito.",
      "q.opening": "Abrindo o WhatsApp...",
      "q.fallback": "Não abriu? Toque aqui para abrir o WhatsApp.",
      "q.msg.hi": "Olá, Jackson! Quero um orçamento.",
      "q.msg.device": "Aparelho",
      "q.msg.defects": "Defeito(s)",
      "q.msg.details": "Detalhes",
      "q.msg.name": "Nome",
      "q.msg.foot": "Enviado pelo site da Central Celulares.",
      "shop.h": "Vitrine",
      "shop.lead": "Alguns produtos da loja. Gostou de algum? Peça pelo WhatsApp.",
      "shop.filters": "Filtrar por categoria",
      "shop.all": "Tudo",
      "cat.protect": "Capas e películas",
      "cat.power": "Carregadores e cabos",
      "cat.audio": "Fones e áudio",
      "cat.mount": "Suportes e extras",
      "shop.from": "a partir de",
      "shop.ask": "Pedir pelo WhatsApp",
      "shop.note": "Preços de referência. Valor e disponibilidade confirmados pelo WhatsApp.",
      "p.case": "Capa transparente anti-impacto",
      "p.silicone": "Capa de silicone",
      "p.glass": "Película de vidro temperado",
      "p.charger": "Carregador turbo USB-C",
      "p.cable": "Cabo USB-C reforçado",
      "p.bank": "Power bank portátil",
      "p.tws": "Fone Bluetooth sem fio",
      "p.wired": "Fone com fio",
      "p.speaker": "Caixa de som Bluetooth",
      "p.carmount": "Suporte veicular",
      "p.ring": "Anel para celular",
      "p.tripod": "Tripé com controle remoto",
      "p.msg": "Olá, Jackson! Vi no site e tenho interesse neste produto: {name}. Ainda tem disponível?",
      "where.h": "Onde estamos",
      "where.addr1": "Shopping Gebai",
      "where.addr2": "Av. Piribebuy, Centro",
      "where.addr3": "Ciudad del Este, Paraguai",
      "where.route": "Como chegar",
      "where.map": "Mapa da localização da Central Celulares no Shopping Gebai",
      "final.h": "Mande o defeito. A gente responde.",
      "final.cta": "Fazer meu orçamento",
      "foot.tag": "Assistência técnica e acessórios para celular.",
      "foot.wa": "WhatsApp",
      "foot.br": "Brasil",
      "foot.py": "Paraguai",
      "dock.quote": "Orçamento",
      "dock.wa": "WhatsApp",
      "wa.generic": "Olá, Jackson! Vim pelo site da Central Celulares.",
    },

    es: {
      "doc.title": "Central Celulares | Servicio técnico de celulares en Shopping Gebai, Ciudad del Este",
      "skip": "Ir al contenido",
      "nav.services": "Fallas",
      "nav.quote": "Presupuesto",
      "nav.shop": "Vitrina",
      "nav.where": "Dónde estamos",
      "nav.lang": "Idioma",
      "nav.cta": "Presupuesto",
      "hero.eyebrow": "Servicio técnico · Shopping Gebai · Ciudad del Este",
      "hero.h1a": "¿Celular con falla?",
      "hero.h1b": "Arreglo rápido.",
      "hero.sub": "Dinos el modelo y la falla. Jackson te responde por WhatsApp con el presupuesto, sin compromiso.",
      "hero.cta": "Pedir mi presupuesto",
      "hero.wa": "Escribir por WhatsApp",
      "hero.where": "Av. Piribebuy, Centro",
      "dg.title": "Diagrama de un celular desarmado en capas: pantalla, batería, placa y carcasa",
      "dg.l1": "01 PANTALLA",
      "dg.l2": "02 BATERÍA",
      "dg.l3": "03 PLACA",
      "dg.l4": "04 CARCASA",
      "trust.label": "Ventajas",
      "trust.1.t": "Presupuesto sin compromiso",
      "trust.1.d": "Decides después de ver el valor.",
      "trust.2.t": "Reparación rápida",
      "trust.2.d": "La mayoría de los servicios sale el mismo día.",
      "trust.3.t": "Garantía en el servicio",
      "trust.3.d": "El plazo se informa en el presupuesto.",
      "trust.4.t": "Repuestos probados",
      "trust.4.d": "Revisamos todo antes de entregar.",
      "how.h": "Cómo funciona",
      "how.1.t": "Cuéntanos la falla",
      "how.1.d": "Elige el modelo y marca lo que está pasando.",
      "how.2.t": "Recibe el presupuesto",
      "how.2.d": "Jackson responde por WhatsApp con valor y plazo.",
      "how.3.t": "Pasa por Shopping Gebai",
      "how.3.d": "Deja el equipo en la tienda y sigue todo por WhatsApp.",
      "svc.h": "Fallas que arreglamos",
      "svc.lead": "Toca tu falla para empezar el presupuesto. ¿No la ves? Marca “Otro problema” y descríbela.",
      "svc.cta": "Pedir presupuesto",
      "d.screen.n": "Pantalla rota",
      "d.screen.d": "Cambio de pantalla y vidrio, con o sin imagen.",
      "d.battery.n": "Batería",
      "d.battery.d": "Dura poco, se descarga rápido o está hinchada.",
      "d.charge.n": "No carga",
      "d.charge.d": "Conector de carga, cable o placa.",
      "d.power.n": "No enciende",
      "d.power.d": "Diagnóstico de placa y fuente de energía.",
      "d.water.n": "Se mojó",
      "d.water.d": "Limpieza de oxidación. Cuanto antes, mejor.",
      "d.camera.n": "Cámara",
      "d.camera.d": "Foto borrosa, negra o lente rota.",
      "d.audio.n": "Sonido y micrófono",
      "d.audio.d": "Altavoz, auricular o micrófono que no funciona.",
      "d.buttons.n": "Botones y sensores",
      "d.buttons.d": "Encendido, volumen y biometría.",
      "d.software.n": "Software",
      "d.software.d": "Se traba, va lento o da error de sistema.",
      "d.other.n": "Otro problema",
      "q.h": "Pide tu presupuesto",
      "q.lead": "Tres pasos y Jackson ya tiene todo para responderte.",
      "q.badge": "Borrador",
      "q.title": "Orden de servicio",
      "q.s1": "1. Marca del equipo",
      "q.s2": "2. Modelo",
      "q.s3": "3. ¿Qué está pasando?",
      "q.s3.hint": "Marca todos los que necesites.",
      "q.model.ph": "Elige el modelo",
      "q.model.first": "Primero elige la marca",
      "q.model.other": "Otro modelo",
      "q.other.l": "¿Cuál es el modelo?",
      "q.other.ph": "Ej.: Moto G54",
      "q.details.l": "¿Quieres dar más detalles? (opcional)",
      "q.details.ph": "Ej.: se cayó ayer, la pantalla enciende pero no responde al toque",
      "q.name.l": "Tu nombre (opcional)",
      "q.name.ph": "Ej.: María",
      "q.route": "Enviar a",
      "q.route.br": "WhatsApp Brasil",
      "q.route.py": "WhatsApp Paraguay",
      "q.sum.h": "Resumen",
      "q.sum.device": "Equipo",
      "q.sum.defects": "Fallas",
      "q.sum.empty": "Aún sin elegir",
      "q.send": "Enviar por WhatsApp",
      "q.hint": "Abre WhatsApp con el mensaje listo. Lo revisas antes de enviar.",
      "q.err.brand": "Elige la marca del equipo.",
      "q.err.model": "Elige el modelo o selecciona “Otro modelo”.",
      "q.err.other": "Escribe el modelo del equipo.",
      "q.err.defects": "Marca al menos una falla.",
      "q.opening": "Abriendo WhatsApp...",
      "q.fallback": "¿No se abrió? Toca aquí para abrir WhatsApp.",
      "q.msg.hi": "¡Hola, Jackson! Quiero un presupuesto.",
      "q.msg.device": "Equipo",
      "q.msg.defects": "Falla(s)",
      "q.msg.details": "Detalles",
      "q.msg.name": "Nombre",
      "q.msg.foot": "Enviado desde el sitio de Central Celulares.",
      "shop.h": "Vitrina",
      "shop.lead": "Algunos productos de la tienda. ¿Te gustó alguno? Pídelo por WhatsApp.",
      "shop.filters": "Filtrar por categoría",
      "shop.all": "Todo",
      "cat.protect": "Fundas y protectores",
      "cat.power": "Cargadores y cables",
      "cat.audio": "Auriculares y audio",
      "cat.mount": "Soportes y extras",
      "shop.from": "desde",
      "shop.ask": "Pedir por WhatsApp",
      "shop.note": "Precios de referencia. Valor y disponibilidad se confirman por WhatsApp.",
      "p.case": "Funda transparente antigolpes",
      "p.silicone": "Funda de silicona",
      "p.glass": "Vidrio templado",
      "p.charger": "Cargador turbo USB-C",
      "p.cable": "Cable USB-C reforzado",
      "p.bank": "Power bank portátil",
      "p.tws": "Auriculares Bluetooth inalámbricos",
      "p.wired": "Auriculares con cable",
      "p.speaker": "Parlante Bluetooth",
      "p.carmount": "Soporte para auto",
      "p.ring": "Anillo para celular",
      "p.tripod": "Trípode con control remoto",
      "p.msg": "¡Hola, Jackson! Lo vi en el sitio y me interesa este producto: {name}. ¿Aún está disponible?",
      "where.h": "Dónde estamos",
      "where.addr1": "Shopping Gebai",
      "where.addr2": "Av. Piribebuy, Centro",
      "where.addr3": "Ciudad del Este, Paraguay",
      "where.route": "Cómo llegar",
      "where.map": "Mapa de la ubicación de Central Celulares en Shopping Gebai",
      "final.h": "Cuéntanos la falla. Te respondemos.",
      "final.cta": "Pedir mi presupuesto",
      "foot.tag": "Servicio técnico y accesorios para celular.",
      "foot.wa": "WhatsApp",
      "foot.br": "Brasil",
      "foot.py": "Paraguay",
      "dock.quote": "Presupuesto",
      "dock.wa": "WhatsApp",
      "wa.generic": "¡Hola, Jackson! Vengo del sitio de Central Celulares.",
    },
  },
};
